"""Initial schema

Revision ID: e3e8676bf048
Revises: 
Create Date: 2026-06-26 23:23:07.586995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3e8676bf048'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempt_results',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('test_title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('incorrect', sa.Integer(), nullable=False),
    sa.Column('time_taken_minutes', sa.Integer(), nullable=False),
    sa.Column('section_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_results_user_id'), 'attempt_results', ['user_id'], unique=False)
    op.create_table('habits',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('planner_days',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('day_name')
    )
    op.create_index(op.f('ix_planner_days_user_id'), 'planner_days', ['user_id'], unique=False)
    op.create_table('study_logs',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_logs_user_id'), 'study_logs', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('streak_history', sa.JSON(), nullable=True),
    sa.Column('daily_study_hours_goal', sa.Float(), nullable=True),
    sa.Column('weekly_practice_hours_goal', sa.Float(), nullable=True),
    sa.Column('monthly_mock_tests_goal', sa.Integer(), nullable=True),
    sa.Column('target_exam_score', sa.Float(), nullable=True),
    sa.Column('preferred_theme', sa.String(), nullable=True),
    sa.Column('accent_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_study_logs_user_id'), table_name='study_logs')
    op.drop_table('study_logs')
    op.drop_index(op.f('ix_planner_days_user_id'), table_name='planner_days')
    op.drop_table('planner_days')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_attempt_results_user_id'), table_name='attempt_results')
    op.drop_table('attempt_results')
    # ### end Alembic commands ###
